### ISSUE TITLE
IndexOutOfRangeException - What am I doing wrong?

### ISSUE THREAD

**Issue by mwasson74** [odinserj/stdump#1]
I'm having "jobs stuck" issue in with Hangfire so I was trying to use this tool to get a report but I can't seem to get it to work.

1. Found my AppPool's PID
2. Attempted to point stdump to the PID
3. Found the service in TaskManager with that PID and created a dump file
4. Attempted to point it to the dmp file

![image](https://github.com/odinserj/stdump/assets/12786751/07581a26-8832-4c41-8400-b707c2cbe2f1)

**Comment by mwasson74** [comment]
@odinserj When you have a moment, please. Thank you!

**Comment by odinserj** [comment]
Sorry for the long delay, I wrapped this part in a try/catch statement, so it shouldn't bring down the whole application now (I'll release a new version today). Looks like there's a bug in ClrMD.
